#!/bin/bash
# Example podman commands generated by ContainerCommandGenerator
# These are reference examples showing the structure of generated commands

# Example 1: Single GPU vLLM deployment
# Model: qwen2.5-7b-instruct-awq
# GPUs: [0]
# Port: 8001
podman run -d --rm \
  --name vllm-qwen2-5-7b-instruct-awq-a1b2c3d4 \
  --device nvidia.com/gpu=0 \
  -v /data/projects/ai/models:/models:ro \
  --shm-size 16g \
  -p 8001:8000 \
  -e CUDA_VISIBLE_DEVICES=0 \
  --label llm-serve=true \
  --label model=qwen2.5-7b-instruct-awq \
  --label runtime=vllm \
  --label gpus=[0] \
  vllm/vllm-openai:latest \
  --model /models/qwen2.5-7b-instruct-awq \
  --max-model-len 8192 \
  --max-num-seqs 4


# Example 2: Multi-GPU vLLM deployment with tensor parallelism
# Model: qwen2.5-72b-instruct-awq
# GPUs: [0, 1]
# Port: 8002
# Tensor Parallel: 2
podman run -d --rm \
  --name vllm-qwen2-5-72b-instruct-awq-b2c3d4e5 \
  --device nvidia.com/gpu=0 \
  --device nvidia.com/gpu=1 \
  -v /data/projects/ai/models:/models:ro \
  --shm-size 16g \
  -p 8002:8000 \
  -e CUDA_VISIBLE_DEVICES=0,1 \
  --label llm-serve=true \
  --label model=qwen2.5-72b-instruct-awq \
  --label runtime=vllm \
  --label gpus=[0,1] \
  vllm/vllm-openai:latest \
  --model /models/qwen2.5-72b-instruct-awq \
  --max-model-len 8192 \
  --tensor-parallel-size 2 \
  --max-num-seqs 4


# Example 3: vLLM with custom environment variables
# Model: llama-3.1-70b-instruct-fp16
# GPUs: [2, 3, 4, 5]
# Port: 8003
# With HuggingFace token
podman run -d --rm \
  --name vllm-llama-3-1-70b-instruct-fp16-c3d4e5f6 \
  --device nvidia.com/gpu=2 \
  --device nvidia.com/gpu=3 \
  --device nvidia.com/gpu=4 \
  --device nvidia.com/gpu=5 \
  -v /data/projects/ai/models:/models:ro \
  --shm-size 16g \
  -p 8003:8000 \
  -e CUDA_VISIBLE_DEVICES=2,3,4,5 \
  -e HF_TOKEN=hf_yourtoken \
  -e TRANSFORMERS_CACHE=/models/.cache \
  --label llm-serve=true \
  --label model=llama-3.1-70b-instruct-fp16 \
  --label runtime=vllm \
  --label gpus=[2,3,4,5] \
  vllm/vllm-openai:latest \
  --model /models/llama-3.1-70b-instruct-fp16 \
  --max-model-len 32768 \
  --tensor-parallel-size 4 \
  --max-num-seqs 8


# Example 4: vLLM with extra runtime arguments
# Model: mistral-7b-instruct-awq
# GPUs: [1]
# Port: 8004
# With trust-remote-code and chunked prefill
podman run -d --rm \
  --name vllm-mistral-7b-instruct-awq-d4e5f6g7 \
  --device nvidia.com/gpu=1 \
  -v /data/projects/ai/models:/models:ro \
  --shm-size 16g \
  -p 8004:8000 \
  -e CUDA_VISIBLE_DEVICES=1 \
  --label llm-serve=true \
  --label model=mistral-7b-instruct-awq \
  --label runtime=vllm \
  --label gpus=[1] \
  vllm/vllm-openai:latest \
  --model /models/mistral-7b-instruct-awq \
  --max-model-len 8192 \
  --max-num-seqs 4 \
  --trust-remote-code \
  --enable-chunked-prefill


# Example 5: vLLM with custom image
# Model: codellama-34b-instruct-awq
# GPUs: [0, 1]
# Port: 8005
# Using specific vLLM version
podman run -d --rm \
  --name vllm-codellama-34b-instruct-awq-e5f6g7h8 \
  --device nvidia.com/gpu=0 \
  --device nvidia.com/gpu=1 \
  -v /data/projects/ai/models:/models:ro \
  --shm-size 16g \
  -p 8005:8000 \
  -e CUDA_VISIBLE_DEVICES=0,1 \
  --label llm-serve=true \
  --label model=codellama-34b-instruct-awq \
  --label runtime=vllm \
  --label gpus=[0,1] \
  custom/vllm:v0.2.7 \
  --model /models/codellama-34b-instruct-awq \
  --max-model-len 16384 \
  --tensor-parallel-size 2 \
  --max-num-seqs 4


# Example 6: vLLM with pipeline parallelism
# Model: qwen2.5-72b-instruct-awq
# GPUs: [0, 1, 2, 3]
# Port: 8006
# Tensor Parallel: 2, Pipeline Parallel: 2
podman run -d --rm \
  --name vllm-qwen2-5-72b-instruct-awq-f6g7h8i9 \
  --device nvidia.com/gpu=0 \
  --device nvidia.com/gpu=1 \
  --device nvidia.com/gpu=2 \
  --device nvidia.com/gpu=3 \
  -v /data/projects/ai/models:/models:ro \
  --shm-size 16g \
  -p 8006:8000 \
  -e CUDA_VISIBLE_DEVICES=0,1,2,3 \
  --label llm-serve=true \
  --label model=qwen2.5-72b-instruct-awq \
  --label runtime=vllm \
  --label gpus=[0,1,2,3] \
  vllm/vllm-openai:latest \
  --model /models/qwen2.5-72b-instruct-awq \
  --max-model-len 32768 \
  --tensor-parallel-size 2 \
  --pipeline-parallel-size 2 \
  --max-num-seqs 4


# Notes:
# - Container names include random 8-char suffix for uniqueness
# - All commands use -d (detached) and --rm (auto-remove on stop)
# - Shared memory size is always 16GB (required for vLLM)
# - Port mapping is always {external}:8000 (vLLM listens on 8000)
# - CUDA_VISIBLE_DEVICES matches the GPU list
# - Labels are used for container discovery and management
# - Model path is relative to the /models mount point in container
